galenos_mini_front/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls")),
]

web/urls.py
from django.urls import path
from . import views
from .views import (
    DashBoardView,
    UpdatedView,
    UserUpdatedView,
    RolUpdatedView,
    PacienteUpdatedView,
    ReservaCreateView,
    ReservaUpdatedView,
    CorreoCreateView,
)


app_name = "web"

urlpatterns = [
    path("", DashBoardView.as_view(), name="crud-dashboard"),
    path("form", views.post_pago, name="formulario"),
    path("form_user", views.post_user, name="formulario-user"),
    path("form_rol", views.post_rol, name="formulario-rol"),
    path("updated", UpdatedView.as_view(), name="updated"),
    path("pago/", views.pago_list, name="pago-list"),
    path("pago/details/<int:pk>/", views.pago_detail, name="pago-detail"),
    path("pago/update/<int:pk>/", views.pago_update, name="pago-update"),
    path("pago/delete/<int:pk>", views.pago_delete, name="pago-delete"),
    path("user/", views.user_list, name="user-list"),
    path("user/details/<int:pk>/", views.user_detail, name="user-detail"),
    path("user/update/<int:pk>/", views.user_update, name="user-update"),
    path("user_updated", UserUpdatedView.as_view(), name="user-updated"),
    path("user/delete/<int:pk>", views.user_delete, name="user-delete"),
    path("rol/", views.rol_list, name="rol-list"),
    path("rol/details/<int:pk>/", views.rol_detail, name="rol-detail"),
    path("rol/update/<int:pk>/", views.rol_update, name="rol-update"),
    path("rol_updated", RolUpdatedView.as_view(), name="rol-updated"),
    path("rol/delete/<int:pk>", views.rol_delete, name="rol-delete"),
    path("paciente/", views.paciente_list, name="paciente-list"),
    path("form_paciente_post", views.post_paciente, name="formulario-paciente-post"),
    path("paciente/details/<int:pk>/", views.paciente_detail, name="paciente-detail"),
    path("paciente/update/<int:pk>/", views.paciente_update, name="paciente-update"),
    path("paciente_updated", PacienteUpdatedView.as_view(), name="paciente-updated"),
    path("paciente/delete/<int:pk>", views.paciente_delete, name="paciente-delete"),
    path("reserva/", views.reserva_list, name="reserva-list"),
    path("reserva/crear/", ReservaCreateView.as_view(), name="reserva-create"),
    path("form_reserva_post", views.post_reserva, name="formulario-reserva-post"),
    path("reserva/details/<int:pk>/", views.reserva_detail, name="reserva-detail"),
    path("reserva/update/<int:pk>/", views.reserva_update, name="reserva-update"),
    path("reserva_updated", ReservaUpdatedView.as_view(), name="reserva-updated"),
    path(
        "reserva_updated/delete/<int:pk>", views.reserva_delete, name="reserva-delete"
    ),
    path("correo/crear/", CorreoCreateView.as_view(), name="correo-create"),
    path("form_correo_post", views.post_correo, name="formulario-correo-post"),
]

web/templates/web/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formulario enviado</title>
</head>
<body>
    <Formulario>Formulario Enviado</Formulario>
</body>
</html>

web/templates/web/form_correo_post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Correos Enviados Exitosamente</title>
  </head>
  <body>
    <Formulario>Correos Enviados Exitosamente</Formulario>
    <div class="navbar-nav w-100">
        <a href="{% url 'web:correo-create' %}">
         </i></i>Volver</a>
      </a>
    </div>

  </body>
</html>

web/templates/web/form_reserva_post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Reserva Creada</title>
  </head>
  <body>
    <Formulario>Reserva Creada</Formulario>
    <div class="navbar-nav w-100">
        <a href="{% url 'web:reserva-list' %}">
         </i></i>Volver</a>
      </a>
    </div>

  </body>
</html>

web/templates/web/form_rol.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formulario enviado</title>
</head>
<body>
    <Formulario>Formulario Enviado</Formulario>
</body>
</html>

web/templates/web/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mini Front</title>
  </head>
  <body></body>
</html>

web/templates/web/paciente_detail.html
{% extends "web/base.html" %}
{% load static %}



{% block content %}




<!-- Content Start -->
<div class="content">

<!-- Blank Start -->




        <!-- Blank Start -->
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Detalle de Paciente</h6>
                <div class="table-responsive">
                    <table class="table">

                        <thead>
                            <tr>
                                <th scope="col">ID Paciente</th>
                                <th scope="col">Correo Electrónico</th>
                                <th scope="col">Rut</th>
                                <th scope="col">Nombres</th>
                                <th scope="col">Apellidos</th>
                                <th scope="col">Previsión</th>
                                <th scope="col">Teléfono</th>
                                <th scope="col">Dirección</th>
                                <th scope="col">Comuna</th>
                                <th scope="col">Fecha de Nacimiento</th>
                                <th scope="col">Contraseña</th>

                            </tr>
                        </thead>

                        <tbody>
                            <tr>

                                <td>{{ obj.id }}</td>
                                <td>{{ obj.email }}</td>
                                <td>{{ obj.rut }}</td>
                                <td>{{ obj.nombres }}</td>
                                <td>{{ obj.apellidos }}</td>
                                <td>{{ obj.prevision_type }}</td>
                                <td>{{ obj.telefono }}</td>
                                <td>{{ obj.direccion }}</td>
                                <td>{{ obj.comuna }}</td>
                                <td>{{ obj.fecha_nacimiento }}</td>
                                <td>{{ obj.password }}</td>

                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Blank End -->
</div>
<!-- Blank End -->

        </div>
        <!-- Content End -->


    <!-- Volver arriba -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>
{% endblock content %}

web/templates/web/paciente_update.html
{% extends "web/base.html" %} {% load static %} {% block content %}

<div class="container-xxl position-relative bg-white d-flex p-0">
  <!-- Content Start -->
  <div class="content">
    <!-- Blank Start -->

    <div class="col-12">
      <div class="bg-light rounded h-100 p-4">
        <h2>Edita Paciente</h2>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-sm btn-warning mt-auto">
            Editar
          </button>
        </form>
        <a href="{% url 'web:paciente-list' %}">Cancel</a>
      </div>
      <hr />
    </div>
    <!-- Blank End -->
  </div>
  <!-- Content End -->

  <!-- Volver arriba -->
  <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"
    ><i class="bi bi-arrow-up"></i
  ></a>
</div>
{% endblock content %}

web/templates/web/pago_list.html
{% extends "web/base.html" %}
{% load static %}

{% block head_title %}Fundación Apoyo - Administrador{% endblock head_title %}


{% block content %}




<!-- Content Start -->
<div class="content">

<!-- Blank Start -->

<div class="col-12">
    <div class="bg-light rounded h-100 p-4">
          <form action="{% url 'web:formulario' %}" method="post">
            {% csrf_token %} {{ form.as_p }}
            <p>
              <label for="medico_id">Medico ID:</label>
              <input
                id="medico_id"
                type="text"
                name="medico_id"
                maxlength="100"
                required
              />
            </p>
            <p>
              <label for="monto">Monto:</label>
              <input id="monto" type="text" name="monto" maxlength="100" required />
            </p>
            <p>
              <label for="tipo_pago">Tipo de pago:</label>
              <input
                id="tipo_pago"
                type="text"
                name="tipo_pago"
                maxlength="100"
                required
              />
            </p>
            <button type="submit" class="btn btn-sm btn-success mt-auto">Crear Pago</button>
          </form>



    </div>


        <!-- Blank Start -->
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Lista de Pagos</h6>
                <div class="table-responsive">
                    <table class="table">

                        <thead>
                            <tr>
                                <th scope="col">ID Pago</th>
                                <th scope="col">ID Médico</th>
                                <th scope="col">Monto</th>
                                <th scope="col">Tipo de Pago</th>
                                <th scope="col">Fecha</th>
                            </tr>
                        </thead>
                        {% for obj in response %}
                        <tbody>
                            <tr>
                                <td><a href="{% url 'web:pago-detail' obj.id %}">{{ obj.id }}</td>
                                <td><a href="{% url 'web:pago-detail' obj.id %}">{{ obj.medico_id }}</td>
                                <td><a href="{% url 'web:pago-detail' obj.id %}">{{ obj.monto }}</td>
                                <td><a href="{% url 'web:pago-detail' obj.id %}">{{ obj.tipo_pago }}</td>
                                <td><a href="{% url 'web:pago-detail' obj.id %}">{{ obj.fecha_pago }}</td>
                                <td><h6><a href="{% url 'web:pago-update' obj.id %}" class="btn btn-sm btn-warning mt-auto">Editar</a></h6></td>
                                <td><h6><a href="{% url 'web:pago-delete' pk=obj.id %}" class="btn btn-sm btn-danger mt-auto" onclick="return confirm('¿Estás seguro de eliminar el pago?')">Eliminar</a></h6></td>

                            </tr>

                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <!-- Blank End -->
</div>
<!-- Blank End -->

        </div>
        <!-- Content End -->


    <!-- Volver arriba -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>
{% endblock content %}

web/templates/web/reserva_create.html
{% extends "web/base.html" %}
{% load static %}


{% load custom_filters %}
{% block content %}




<!-- Content Start -->
<div class="content">

<!-- Blank Start -->


<div class="col-12">
    <div class="bg-light rounded h-100 p-4">
          <form action="{% url 'web:formulario-reserva-post' %}" method="post">
            {% csrf_token %} {{ form.as_p }}
            <p>
              <label for="id_paciente">ID Paciente:</label>
              <input
                id="id_paciente"
                type="text"
                name="id_paciente"
                maxlength="100"
                required
              />
            </p>
            <p>
              <label for="id_medico">ID Medico:</label>
              <input
                id="id_medico"
                type="text"
                name="id_medico"
                maxlength="100"
                required
              />
            </p>
            <p>
              <label for="fecha">Fecha:</label>
              <input
                id="fecha"
                type="date"
                name="fecha"
                maxlength="100"
                required
              />
            </p>
            <p>
              <label for="hora_inicio">Hora Inicio:</label>
              <input
                id="hora_inicio"
                type="time"
                name="hora_inicio"
                maxlength="100"
                required
              />
            </p>
            <p>
              <label for="hora_termino">Hora Termino:</label>
              <input
                id="hora_termino"
                type="time"
                name="hora_termino"
                maxlength="100"
                required
              />
            </p>


            <button type="submit" class="btn btn-sm btn-success mt-auto">Crear Reserva</button>
          </form>



    </div>
</div>
<!-- Blank End -->

        </div>
        <!-- Content End -->


    <!-- Volver arriba -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>
{% endblock content %}

web/templates/web/reserva_list.html
{% extends "web/base.html" %}
{% load static %}


{% load custom_filters %}
{% block content %}




<!-- Content Start -->
<div class="content">

<!-- Blank Start -->


<div class="col-12">


    <h4 class="mb-4">Puedes Crear una Reserva con el boton "Crear Reserva".</h4>
    <a href="{% url 'web:reserva-create' %}" class="btn btn-outline-primary btn-rounded"><i class="fa-regular fa-calendar-check fa-lg"><strong>Crear Reserva</strong></i></a>


      <!-- Blank Start -->
      <div class="col-12">
        <div class="bg-light rounded h-100 p-4">
            <h6 class="mb-4">Lista de Pacientes</h6>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID Reserva</th>
                            <th scope="col">ID Paciente</th>
                            <th scope="col">ID Médico</th>
                            <th scope="col">Fecha Reserva</th>
                            <th scope="col">Hora Inicio</th>
                            <th scope="col">Hora Termino</th>

                        </tr>
                    </thead>
                    {% for obj in response %}
                    <tbody>
                        <tr>

                            <td><a href="{% url 'web:reserva-detail' obj.id %}">{{ obj.id }}</td>
                            <td><a href="{% url 'web:reserva-detail' obj.id %}">{{ obj.id_paciente }}</td>
                            <td><a href="{% url 'web:reserva-detail' obj.id %}">{{ obj.id_medico }}</td>
                            <td><a href="{% url 'web:reserva-detail' obj.id %}">{{ obj.fecha }}</td>
                            <td><a href="{% url 'web:reserva-detail' obj.id %}">{{ obj.hora_inicio }}</td>
                            <td><a href="{% url 'web:reserva-detail' obj.id %}">{{ obj.hora_termino }}</td>
                            <td><h6><a href="{% url 'web:reserva-update' obj.id %}" class="btn btn-sm btn-warning mt-auto">Editar</a></h6></td>
                            <td><h6><a href="{% url 'web:reserva-delete' pk=obj.id %}" class="btn btn-sm btn-danger mt-auto" onclick="return confirm('¿Estás seguro de eliminar la reserva?')">Eliminar</a></h6></td>


                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
      </div>
      <!-- Blank End -->
</div>
<!-- Blank End -->

        </div>
        <!-- Content End -->


    <!-- Volver arriba -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>
{% endblock content %}

web/templates/web/reserva_update.html
{% extends "web/base.html" %} {% load static %} {% block content %}

<div class="container-xxl position-relative bg-white d-flex p-0">
  <!-- Content Start -->
  <div class="content">
    <!-- Blank Start -->

    <div class="col-12">
      <div class="bg-light rounded h-100 p-4">
        <h2>Edita Reserva</h2>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-sm btn-warning mt-auto">
            Editar
          </button>
        </form>
        <a href="{% url 'web:reserva-list' %}">Cancel</a>
      </div>
      <hr />
    </div>
    <!-- Blank End -->
  </div>
  <!-- Content End -->

  <!-- Volver arriba -->
  <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"
    ><i class="bi bi-arrow-up"></i
  ></a>
</div>
{% endblock content %}

web/templates/web/scripts.html
{% load static %}
<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'users/lib/chart/chart.min.js' %}"></script>
<script src="{% static 'users/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'users/lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'users/lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'users/lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'users/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'users/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'users/js/main.js' %}"></script>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"
></script>

web/templates/web/updated.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Exito Actualizando</title>
  </head>
  <body>
    <Formulario>Exito Actualizando</Formulario>
  </body>
</html>

web/templates/web/user_detail.html
{% extends "web/base.html" %}
{% load static %}



{% block content %}




<!-- Content Start -->
<div class="content">

<!-- Blank Start -->




        <!-- Blank Start -->
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Detalle de Usuario</h6>
                <div class="table-responsive">
                    <table class="table">

                        <thead>
                            <tr>
                                <th scope="col">Nombre de Usuario</th>
                                <th scope="col">Email</th>
                                <th scope="col">Password</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>

                                <td>{{ obj.username }}</td>
                                <td>{{ obj.email }}</td>
                                <td>{{ obj.password }}</td>

                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Blank End -->
</div>
<!-- Blank End -->

        </div>
        <!-- Content End -->


    <!-- Volver arriba -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>
{% endblock content %}